[package]
authors = ["Sakamoto Yoshiki <g196010r@icu.ac.jp>"]
description = "Crate of loading cifar10"
documentation = "https://docs.rs/cifar_10_loader/"
license = "MIT"
name = "cifar_10_loader"
readme = "README.md"
repository = "https://github.com/29rou/cifar-10-loader-rs"
version = "0.1.17"

[dependencies]
rand = "0.3.17"
rayon = "0.8.2"
regex = "0.2.2"
walkdir = "2.0.1"

[dependencies.clippy]
optional = true
version = "0.0.166"

[dependencies.image]
default-features = false
version = "0.17.0"

[dependencies.itertools]
default-features = false
version = "0.7.1"


[lib]
name = "cifar_10_loader"
path = "./src/lib.rs"
